### PR TITLE
Dev/xdpdump missing btf

### LINKED ISSUE #112: xdp-dump: add more clear error message when BTF information is not found.
See output below, i.e. fix `ERROR: Can't find function '' on interface!` to be more specific as `-vv` is not used by default.

```
# ./xdpdump -i enp3s0f1 --rx-capture entry,exit -w capture.pcap -vv 
Current rlimit 67108864 already >= minimum 1048576
libxdp: No BTF for prog ID 11
libxdp: No BTF found for program
libxdp: Found legacy program with id 11 and 0 component progs
No BTF found for program
ERROR: Can't find function '' on interface!
```

### PR DESCRIPTION
**Pull request by chaudron**
Fixes #112 and a crash found during playing with command line options.

### CODE REVIEW

File: xdp-dump/xdpdump.c [hunk 1]
```diff
@@ -924,6 +924,20 @@ static int match_target_function(struct dumpopt *cfg,
...
+/*****************************************************************************
+ * check_btf()
+ *****************************************************************************/
+static bool check_btf(struct xdp_program *prog)
+{
+	if (xdp_program__btf(prog))
+		return true;
+
+	pr_warn("ERROR: The loaded XDP program has no BTF information, "
+		"which xdpdump requires!\n");
```
Comment (tohojo) [inline xdp-dump/xdpdump.c:937]: Small nit: this could be interpreted to mean "xdpdump requires that there is no BTF information". So maybe change it to something like "xdpdump requires BTF information, but that is missing from the loaded XDP program"?

Comment (chaudron) [reply xdp-dump/xdpdump.c:937]: When reading again you are right will update pull req.
